<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0TH2U9N4" failures="1" tests="4" name="RetryMultipleFailedTest" time="0.104" errors="0" timestamp="2025-03-22T11:33:55 IST">
  <testcase classname="advancedSelenium.RetryLogic" name="test2" time="0.016"/>
  <testcase classname="advancedSelenium.RetryLogic" name="test3" time="0.012">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="advancedSelenium.RetryLogic" name="test3" time="0.007">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="advancedSelenium.RetryLogic" name="test3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at advancedSelenium.RetryLogic.test3(RetryLogic.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- RetryMultipleFailedTest -->
